name = "fs-child"
version = "0.1.0"
description = "filesystem child actor"
component_path = "/Users/colinrozzi/work/actors/fs-child/target/wasm32-unknown-unknown/release/fs_child.wasm"
init_data = "/Users/colinrozzi/work/actors/fs-child/assets/init.json"

[interface]
implements = "ntwk:theater/single-actor"
requires = []

[[handlers]]
type = "runtime"
config = {}

[[handlers]]
type = "filesystem"
config = {}